language: php

php:
- 7.2
- 7.3

env:
    matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

services:
- mysql

sudo: required

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
- mysql -e 'CREATE DATABASE test_ms;'

script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --configuration phpunit.xml.travis

after_script:
- php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
