language: php

php:
- 7.1
- 7.2
- 7.3

env:
    matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

services:
- mysql
- postgresql

sudo: required

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
- mysql -e 'CREATE DATABASE test_ms;'
- psql -c 'CREATE DATABASE test_ms;' -U postgres
- psql -c 'CREATE ROLE root SUPERUSER LOGIN;' -U postgres

script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --configuration phpunit.xml.travis

after_script:
- php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
